# Gaussian elimination a.k.a "matrix operations"

<br>

$$\Large
A x =y$$

<br>

$$\large
\left(
\begin{array}{cccc}
 a_{0,0} & a_{0,1} & a_{0,2} &
   a_{0,3} \\
 a_{1,0} & a_{1,1} & a_{1,2} &
   a_{1,3} \\
 a_{2,0} & a_{2,1} & a_{2,2} &
   a_{2,3} \\
 a_{3,0} & a_{3,1} & a_{3,2} &
   a_{3,3} \\
\end{array}
\right) \left(
\begin{array}{c}
 x_{0} \\
 x_{1} \\
 x_{2} \\
 x_{3} \\
\end{array}
\right) \ = \ \left(
\begin{array}{c}
 y_{0} \\
 y_{1} \\
 y_{2} \\
 y_{3} \\
\end{array}
\right)
$$

<br>
<br>

## Augmented matrix

$$\large
S \ = \ \left(
\begin{array}{cccccc}
 a_{0,0} & a_{0,1} & a_{0,2} &
   a_{0,3} & | & y_{3} \\
 a_{1,0} & a_{1,1} & a_{1,2} &
   a_{1,3} & | & y_{3} \\
 a_{2,0} & a_{2,1} & a_{2,2} &
   a_{2,3} & | & y_{3} \\
 a_{3,0} & a_{3,1} & a_{3,2} &
   a_{3,3} & | & y_{3} \\
\end{array}
\right)
$$



<br>
<br>

# The rules
* Multiply any row by a constant.

$$\large
r \ \leftarrow \ c\, r 
$$


* Add any row to another.

  $$\large
  r \ \leftarrow \ r + s 
  $$

* Swap rows

  $$\large
  \text{t} \ \leftarrow \ r 
  $$
  
  $$\large
  \text{r} \ \leftarrow \ \text{s} 
  $$
  
  $$\large
  \text{s} \ \leftarrow \ \text{t} 
  $$

I'm using the $\leftarrow$ to mean what the `=` sign usually means for computer languages (e.g. Python). It means taking the quantity on the right-hand side and making the left-hand side symbol equal to that thing. The $\leftarrow$ notation is common in numerical analysis articles and some textbooks.

<br>
<br>

However, the swap is (technically) redundant. 

$$\large
r \ \leftarrow \ r + s 
$$
$$
\large
s \ \leftarrow \ r - s 
$$
$$
\large
r \ \leftarrow \ r - s
$$

I'm not recommending that you use this trick when swapping data. But it's nice to know that row addition and scalar multiplication are all you need.  

## In-place operations

Given the concept of $\leftarrow$, many programming languages come with ``in-place'' operations that do simple arithmetic to a variable and put the result back into the same variable.


<br>
<br>

In [41]:
r = 3
s = 2
print(r,s)

r += s  # r = r + s
s *= -1 # s = -s
s += r  # s = s + r
r -= s  # r = r - s
print(r,s)

3 2
2 3


In [42]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [43]:
n = 5
A = np.random.random((n,n))
y = np.random.random((n,))

print(A,'\n')
print(y,'\n')

[[0.7632 0.513  0.8242 0.6842 0.7759]
 [0.8137 0.219  0.6289 0.3192 0.1158]
 [0.6506 0.6702 0.1963 0.9889 0.452 ]
 [0.9957 0.796  0.7916 0.0156 0.8732]
 [0.3793 0.3118 0.211  0.2489 0.0229]] 

[0.3646 0.3995 0.6426 0.5873 0.4153] 



In [44]:
A_inv = np.linalg.inv(A)
print(A_inv,'\n')

[[-2.5011  2.9824  1.8875  0.9681 -4.5083]
 [ 0.6571 -2.7164 -1.0595  0.1707  5.8748]
 [ 2.6577 -1.3852 -2.5225 -0.9916  4.5538]
 [ 0.7501  0.0025  0.4894 -0.9219  0.0658]
 [-0.1701  0.3314  1.0918  0.8011 -4.3445]] 



In [45]:
A_inv @ A 

array([[ 1., -0., -0., -0., -0.],
       [-0.,  1., -0.,  0., -0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1., -0.],
       [-0.,  0.,  0.,  0.,  1.]])

In [46]:
x = np.linalg.solve(A,y)
print(x,'\n')

[ 0.1892  1.0132  0.1032  0.0749 -0.5616] 



In [47]:
np.max(np.abs(A @ x - y))

1.1102230246251565e-16

In [48]:
def test_inverse_error(n):

    A = np.random.random((n,n))
    y = np.random.random((n,))

    x = np.linalg.solve(A,y)

    return np.max(np.abs(A @ x - y))

In [49]:
%timeit 1+1

9.43 ns ± 0.104 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [50]:
%timeit test_inverse_error(5)

9.06 µs ± 288 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [51]:
%timeit test_inverse_error(50)

41.3 µs ± 290 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [52]:
%timeit test_inverse_error(500)

6.17 ms ± 62.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [53]:
%timeit test_inverse_error(5000)

4.34 s ± 53.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [54]:
def build_S(A,y): 
    
    m, n = A.shape

    S = np.zeros((m,n+1))

    S[:,:-1] = A
    S[:,-1]  = y
    
    return S

In [55]:
#Try to get the logic of Gaussian elimination one step at a time. 

S = build_S(A,y)

j = 0 

S[j] /= S[j,j]

k = 1

S[k] -= S[j] * S[k,j]

print(S)

S[j] /= S[j,j]

for k in range(1,n):
    S[k] -= S[j] * S[k,j]

print(S)

[[ 1.      0.6721  1.0799  0.8965  1.0167  0.4777]
 [ 0.     -0.3279 -0.2498 -0.4103 -0.7115  0.0108]
 [ 0.6506  0.6702  0.1963  0.9889  0.452   0.6426]
 [ 0.9957  0.796   0.7916  0.0156  0.8732  0.5873]
 [ 0.3793  0.3118  0.211   0.2489  0.0229  0.4153]]
[[ 1.      0.6721  1.0799  0.8965  1.0167  0.4777]
 [ 0.     -0.3279 -0.2498 -0.4103 -0.7115  0.0108]
 [ 0.      0.233  -0.5062  0.4057 -0.2094  0.3318]
 [ 0.      0.1268 -0.2836 -0.877  -0.139   0.1117]
 [ 0.      0.0569 -0.1986 -0.0911 -0.3627  0.2341]]


<br>
<br>
We can do operations to multiple right-hand-side vectors at the same time.

In [66]:
n = 5
p = 2
A = np.random.random((n,n))
y = np.random.random((n,p))

x = np.linalg.solve(A,y)

print('A:')
print(A,'\n')
print('y:')
print(y,'\n')

A:
[[0.6778 0.684  0.3509 0.7479 0.3295]
 [0.9738 0.3855 0.6974 0.1157 0.881 ]
 [0.0114 0.1374 0.1171 0.4485 0.7061]
 [0.037  0.285  0.2774 0.2526 0.8313]
 [0.4033 0.5254 0.7048 0.7873 0.3339]] 

y:
[[0.7118 0.6483]
 [0.9766 0.5665]
 [0.606  0.2273]
 [0.355  0.2776]
 [0.0386 0.849 ]] 



In [67]:
S = np.zeros((n,n+y.shape[1]))
S[:,:n] = A
S[:,n:] = y
print('S=[A,y]:')
print(S)

S=[A,y]:
[[0.6778 0.684  0.3509 0.7479 0.3295 0.7118 0.6483]
 [0.9738 0.3855 0.6974 0.1157 0.881  0.9766 0.5665]
 [0.0114 0.1374 0.1171 0.4485 0.7061 0.606  0.2273]
 [0.037  0.285  0.2774 0.2526 0.8313 0.355  0.2776]
 [0.4033 0.5254 0.7048 0.7873 0.3339 0.0386 0.849 ]]


In [68]:
def forward_sweep(S,show=True):
    n = len(S)
    for j in range(n):
        S[j,j:] /= S[j,j]
        
        if show: 
            print(S,'\n')
            
        for k in range(j+1,n):
            S[k,j:] -= S[j,j:]*S[k,j]
            
            if show: 
                print(S,'\n')
    pass

In [69]:
forward_sweep(S)

[[1.     1.0091 0.5178 1.1034 0.4861 1.0502 0.9565]
 [0.9738 0.3855 0.6974 0.1157 0.881  0.9766 0.5665]
 [0.0114 0.1374 0.1171 0.4485 0.7061 0.606  0.2273]
 [0.037  0.285  0.2774 0.2526 0.8313 0.355  0.2776]
 [0.4033 0.5254 0.7048 0.7873 0.3339 0.0386 0.849 ]] 

[[ 1.      1.0091  0.5178  1.1034  0.4861  1.0502  0.9565]
 [ 0.     -0.5972  0.1932 -0.9589  0.4077 -0.0462 -0.3649]
 [ 0.0114  0.1374  0.1171  0.4485  0.7061  0.606   0.2273]
 [ 0.037   0.285   0.2774  0.2526  0.8313  0.355   0.2776]
 [ 0.4033  0.5254  0.7048  0.7873  0.3339  0.0386  0.849 ]] 

[[ 1.      1.0091  0.5178  1.1034  0.4861  1.0502  0.9565]
 [ 0.     -0.5972  0.1932 -0.9589  0.4077 -0.0462 -0.3649]
 [ 0.      0.1259  0.1112  0.4359  0.7005  0.5941  0.2164]
 [ 0.037   0.285   0.2774  0.2526  0.8313  0.355   0.2776]
 [ 0.4033  0.5254  0.7048  0.7873  0.3339  0.0386  0.849 ]] 

[[ 1.      1.0091  0.5178  1.1034  0.4861  1.0502  0.9565]
 [ 0.     -0.5972  0.1932 -0.9589  0.4077 -0.0462 -0.3649]
 [ 0.      0.1259  0.11

In [70]:
def back_sweep(S,show=True):
    n = len(S)
    for j in range(1,n):
        for k in range(n-j):
            S[k,n-j:] -= S[k,n-j]*S[n-j,n-j:]
            
            if show: 
                print(S,'\n')
    pass

In [71]:
back_sweep(S,show=True)

[[ 1.      1.0091  0.5178  1.1034  0.      0.65    0.9855]
 [ 0.      1.     -0.3235  1.6056 -0.6826  0.0773  0.611 ]
 [ 0.      0.      1.      1.539   5.1759  3.8456  0.9184]
 [ 0.      0.      0.      1.      1.0885  1.4213  0.3112]
 [ 0.      0.      0.      0.      1.      0.8234 -0.0598]] 

[[ 1.      1.0091  0.5178  1.1034  0.      0.65    0.9855]
 [ 0.      1.     -0.3235  1.6056  0.      0.6394  0.5702]
 [ 0.      0.      1.      1.539   5.1759  3.8456  0.9184]
 [ 0.      0.      0.      1.      1.0885  1.4213  0.3112]
 [ 0.      0.      0.      0.      1.      0.8234 -0.0598]] 

[[ 1.      1.0091  0.5178  1.1034  0.      0.65    0.9855]
 [ 0.      1.     -0.3235  1.6056  0.      0.6394  0.5702]
 [ 0.      0.      1.      1.539   0.     -0.416   1.228 ]
 [ 0.      0.      0.      1.      1.0885  1.4213  0.3112]
 [ 0.      0.      0.      0.      1.      0.8234 -0.0598]] 

[[ 1.      1.0091  0.5178  1.1034  0.      0.65    0.9855]
 [ 0.      1.     -0.3235  1.6056  0.      0.63

In [95]:
print(A @ S[:,-y.shape[1]:] - y)

[[ 0.  0.]
 [ 0. -0.]
 [-0.  0.]
 [-0.  0.]
 [-0.  0.]]


<br>
<br>

Here are some interesting matrices that we can use as examples. Things like this occur in quantum information science. 

$\large n=4$
$$\large
I = \left(
\begin{array}{cccc}
 1 & 0 & 0 & 0  \\
 0 & 1 & 0 & 0  \\
 0 & 0 & 1 & 0  \\
 0 & 0 & 0 & 1  \\
\end{array}
\right) , \qquad \qquad E = \frac{1}{n}\,\left(
\begin{array}{cccc}
 1 & 1 & 1 & 1  \\
 1 & 1 & 1 & 1  \\
 1 & 1 & 1 & 1  \\
 1 & 1 & 1 & 1  \\
\end{array}
\right)
$$

<br>

<br>

## Algebra 

$$\large 
I^{2} = I, \qquad I E = E I = E, \qquad E^{2} = E
$$

<br>
<br>

$$\large
(a\, I + b \, E)\, (c\, I + d \, E) \ = \ a c \, I + ( a d + b c + b d ) \, E
$$

<br>


<br>

Also

$$\large
(\,a\, I + b \, E\,)^{-1} \ = \ \frac{1}{a}\, I  - \frac{b}{a ( a + b )}\, E
$$

<br>

There's only a true problem if $a = 0$ or $b = - a$. 

<br>

But depending on the values, we can get something that fails with simple Gaussian elimination. It's ok when this happens; we just need to swap.

In [124]:
def M(n,a,b):
    return a * np.eye(n) + (b/n) * np.ones((n,n))

In [125]:
n = 5
a, b = 3, 2 
c, d = 4, 5
M(n,a,b) @ M(n,c,d) - M(n, a*c, a*d + b*c + b*d)

array([[-0.,  0.,  0.,  0.,  0.],
       [ 0., -0.,  0.,  0.,  0.],
       [ 0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [144]:
n = 4
a = 3
b = -n
A = M(n,a,b)
y = np.random.random((n,1))
x = np.linalg.solve(A,y)

print('A:')
print(A,'\n')
print('y:')
print(y,'\n')
print('x:')
print(x)

A:
[[ 2. -1. -1. -1.]
 [-1.  2. -1. -1.]
 [-1. -1.  2. -1.]
 [-1. -1. -1.  2.]] 

y:
[[0.5956]
 [0.9954]
 [0.8583]
 [0.4466]] 

x:
[[-0.7668]
 [-0.6335]
 [-0.6792]
 [-0.8165]]


In [145]:
print(np.linalg.inv(A))

[[ 0.     -0.3333 -0.3333 -0.3333]
 [-0.3333  0.     -0.3333 -0.3333]
 [-0.3333 -0.3333 -0.     -0.3333]
 [-0.3333 -0.3333 -0.3333 -0.    ]]


In [146]:
S = build_S(A,y[0])

In [147]:
S

array([[ 2.    , -1.    , -1.    , -1.    ,  0.5956],
       [-1.    ,  2.    , -1.    , -1.    ,  0.5956],
       [-1.    , -1.    ,  2.    , -1.    ,  0.5956],
       [-1.    , -1.    , -1.    ,  2.    ,  0.5956]])

In [148]:
forward_sweep(S)

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [-1.      2.     -1.     -1.      0.5956]
 [-1.     -1.      2.     -1.      0.5956]
 [-1.     -1.     -1.      2.      0.5956]] 

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [ 0.      1.5    -1.5    -1.5     0.8934]
 [-1.     -1.      2.     -1.      0.5956]
 [-1.     -1.     -1.      2.      0.5956]] 

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [ 0.      1.5    -1.5    -1.5     0.8934]
 [ 0.     -1.5     1.5    -1.5     0.8934]
 [-1.     -1.     -1.      2.      0.5956]] 

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [ 0.      1.5    -1.5    -1.5     0.8934]
 [ 0.     -1.5     1.5    -1.5     0.8934]
 [ 0.     -1.5    -1.5     1.5     0.8934]] 

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [ 0.      1.     -1.     -1.      0.5956]
 [ 0.     -1.5     1.5    -1.5     0.8934]
 [ 0.     -1.5    -1.5     1.5     0.8934]] 

[[ 1.     -0.5    -0.5    -0.5     0.2978]
 [ 0.      1.     -1.     -1.      0.5956]
 [ 0.      0.      0.     -3.      1.78

/var/folders/9t/l8z7ryss4ksbcwtsn1rzxln00000gn/T/ipykernel_53481/298669992.py:4: RuntimeWarning: divide by zero encountered in divide
  S[j,j:] /= S[j,j]
/var/folders/9t/l8z7ryss4ksbcwtsn1rzxln00000gn/T/ipykernel_53481/298669992.py:4: RuntimeWarning: invalid value encountered in divide
  S[j,j:] /= S[j,j]
